import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import Header from './components/Header';
import "./globals.css";
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "blog",
  description: "Generated by create next app",
  alternates: {
    types: {
      'application/rss+xml': '/rss.xml'
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.variable} ${playfair.variable} antialiased`}>
      <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:top-0 focus:left-0 focus:bg-surface focus:text-foreground p-4">
        Skip to main content
      </a>
      <div className="flex flex-col min-h-screen">
          <Header />
          <main id="main-content" className="flex-grow">
            <div className="container mx-auto px-8 py-8">
              {children}
            </div>
          </main>
          <footer className="bg-surface">
            <div className="container mx-auto py-4 text-center text-sm text-text-secondary">
              &copy; {new Date().getFullYear()} blog. All rights reserved.
              <div className="mt-2 text-xs text-text-secondary">
                Built at {process.env.NEXT_PUBLIC_BUILD_TIME} | v{process.env.NEXT_PUBLIC_VERSION}
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
