import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import Header from './components/Header';
import "./globals.css";
import PageContainer from './components/PageContainer';
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "blog",
  description: "Generated by create next app",
  alternates: {
    types: {
      'application/rss+xml': '/rss.xml'
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${playfair.variable} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow">
            <PageContainer>
              {children}
            </PageContainer>
          </main>
          <footer className="bg-gray-100">
            <div className="container mx-auto px-4 py-4 text-center text-sm text-gray-600">
              &copy; {new Date().getFullYear()} blog. All rights reserved.
            </div>
          </footer>
          <div className="text-center text-xs text-gray-500 py-2">
            Built at {process.env.NEXT_PUBLIC_BUILD_TIME} | v{process.env.NEXT_PUBLIC_VERSION}
          </div>
        </div>
      </body>
    </html>
  );
}
